# action.yaml
name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
env:
  REGION: Monday
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    # - name: configure aws credentials
    #   uses: aws-actions/configure-aws-credentials@v2
    #   with:
    #     role-to-assume: arn:aws:iam::772371761711:role/github-actions-role
    #     role-session-name: github-actions-role
    #     aws-region: {"ap-southeast-1"}
    - name: run-ssm-command
      id: run-ssm-command
      run: python src/get_num_square.py
      shell: bash