# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: deployment
on:
  push
env:
  TAG_NAME : "akhil-test"
  AWS_REGION : "ap-southeast-1"
  TARGET_BRANCH : TARGET_BRANCH
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772371761711:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependancies
        run: npm install
      - name: Run Test
        run: npm test
      - name: Build
        run: npm run build && zip -r dist.zip dist/
      - name: copy to s3
        run: ls -al; aws s3 cp ./dist.zip s3://github-actions-build/build/
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772371761711:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install Dependencies
        run: pip install -r ./ci/requirements.txt
        shell: bash
      - name:  run_ssm
        timeout-minutes: 15
        run: |
          python3 ./ci/run_ssm.py