# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: deployment
on:
  workflow_dispatch:
    inputs:
      instance_ids:
        type: choice
        description: select instance ids
        options: 
        - i-06fc1c8dc36bd1870
env:
  TAG_NAME : "akhil-test"
  AWS_REGION : "ap-southeast-1"
  TARGET_BRANCH : TARGET_BRANCH
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: Install dependancies
        run: aws --version
