# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow
on:
  push
env:
  BUCKET_NAME : "cloudbank-terraform-backend"
  AWS_REGION : "ap-southeast-2"
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772371761711:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash
      # Upload a file to AWS s3
      - name:  list s3 file
        run: |
          python3 ./src/get_num_square.py