name: Test Action
on: [push]

jobs:
  get-num-square:
    runs-on: ubuntu-latest
    name: Returns the number square
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::772371761711:role/github-actions-role
          role-session-name: samplerolesession
          aws-region: "ap-southeast-1"
      - name: Fetch num squared
        id: get_square
        uses: ./
        with:
          num: 11
      - name: Print the square
        run: echo "${{ steps.get_square.outputs.num_squared }}"